# AppVeyor Build number is incremental and not related to actual version number of the product
version: '{build}'

image: Visual Studio 2019

init:
  - cmd: git config --global core.autocrlf true

environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

build_script:
  - ps: Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile .\dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -Runtime dotnet -Version 2.0.7 # Required for building the netcoreapp2.1 FrontendWeb (Razor throws an error otherwise)
  - ps: .\dotnet-install.ps1 -Runtime dotnet -Version 2.1.23
  - ps: .\dotnet-install.ps1 -Runtime dotnet -Version 3.1.10
  - ps: .\dotnet-install.ps1 -Runtime dotnet -Version 5.0.12
  - ps: .\dotnet-install.ps1 -Version 6.0.100
  - ps: .\build.ps1

test: off

artifacts:
  - path: artifacts\nuget\*.nupkg
    name: NuGet
  - path: artifacts\nuget\*.snupkg
    name: Symbols

# Deploy every successful build (except PRs) to development feed
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
